name: 'Publish package to CodeArtifact'
description: 'Publish package to CodeArtifact'

inputs:
  package:  # id of input
    description: 'The package where to bump the version.'
    required: true
  aws_domain:
    description: 'The AWS codeartifact domain where to push the package.'
    required: true
  aws_repository:
    description: 'The AWS codeartifact repository where to push the code.'

runs:
  using: "composite"
  steps:
    # install dependencies
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.13"

    - name: Install Twine
      run: uv tool install twine
      shell: bash

    # build package
    - name: Build Package
      run: cd ${PACKAGE} && uv build
      shell: bash
      env:
        PACKAGE: ${{ inputs.package }}

    # publish to CodeArtifact
    - name: Publish Package
      run: |
        cd ${PACKAGE} &&
        aws codeartifact login --tool twine --domain ${DOMAIN} --repository ${REPOSITORY} &&
        twine upload --repository codeartifact dist/*
      shell: bash
      env:
        PACKAGE: ${{ inputs.package }}
        DOMAIN: ${{ inputs.aws_domain }}
        REPOSITORY: ${{ inputs.aws_repository }}
