import enum

import pydantic


class Gender(enum.Enum):
    male = "male"
    female = "female"
    undefined = "undefined"


class Date(pydantic.BaseModel):
    start: str = ...
    end: str | None = None


class Runner(pydantic.BaseModel):
    first_name: str = ...
    last_name: str = ...
    birth_year: int = ...
    gender: Gender = ...
    license: str | None = None
    category: str = ...
    race_number: int = ...


class Rank(pydantic.BaseModel):
    scratch: int = ...
    gender: int = ...
    category: int = ...


class Result(pydantic.BaseModel):
    runner: Runner = ...
    time: int = ...
    rank: Rank = ...


class Competition(pydantic.BaseModel):
    name: str = ...
    date: Date = ...
    distance: float = ...
    results: list[Result] = pydantic.Field(default_factory=list)
    
    def __hash__(self):
        return hash(self.name)
