name: Run Pytest on Merge to Main

on:
  pull_request:
    paths:
      - "services/**"
    branches:
      - 'main'

env:
  AWS_REGION : eu-west-1
  AWS_ACCOUNT_ID: 910438175741

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  # Filter out packages that have no changes
  filter-changed-services:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.subdirectories }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: filter
        uses: './.github/actions/collect_changed_subdirectories'
        with:
          directory: "services"
          commit_sha: ${{ github.sha }}

  # Pre-commit checks: is the code well written?
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    needs: [ filter-changed-services ]
    strategy:
      matrix:
        service: ${{ fromJSON(needs.filter-changed-services.outputs.services) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: "Pre-Commit checks"
        uses: "./.github/actions/pre_commit"
        with:
          package: "services/${{ matrix.service }}"
          source_code: "src"

  # Unittests
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: [ filter-changed-services ]
    strategy:
      matrix:
        python-version: [ "3.12" ]
        service: ${{ fromJSON(needs.filter-changed-services.outputs.services) }}
    env:
      ENV: dev
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: 'eu-west-1'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE }}
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        uses: ./.github/actions/pytest
        with:
          parent_directory: "services"
          name: ${{ matrix.service }}
          source_code: "src"
          aws_deployment_account_id: ${{ secrets.AWS_DEPLOYMENT_ACCOUNT_ID }}
